### PR TITLE
Support passing different args to chrome cmd

### PR DESCRIPTION
**Pull request by cyu**

### CODE REVIEW

**Comment by jeremyhaile** [comment]
@cyu why did you decide to add config options vs just changing the defaults for all renders? Do we have a case where we don't want this behavior?

**Comment by cyu** [comment]
@jeremyhaile We could run PDF mage with these options, but the options will wait 10 seconds before converting the page to a PDF.  There isn't a reason to make PDF printing to wait in existing cases where we don't need to wait.

**Comment by jeremyhaile** [comment]
Why do we need to wait 10 seconds now? That's a pretty long time for the user to wait on the export....

**Comment by cyu** [comment]
Need to wait for the ember view to render.  I copied that from an example I found, so I can probably lower that number down. What do you think?  2 seconds, or should we try lower?

**Comment by bhirsch42** [comment]
Could PDF Mage add a callback method to `window` that ember pdf pages can call after they're done loading? @cyu @jeremyhaile

**Comment by jeremyhaile** [comment]
@cyu @bhirsch42 any time based interval seems error prone, or just laggy to the user. If there is some way to use a callback that indicates it's finished rendering to chrome, that'd be great.

That being said, I think server-side rendering the view and just returning it is the easiest option here. Static report views don't need to load Ember, be JS-rendered, etc. Everything would be faster and simpler if we just server-side rendered the PDF.

**Comment by bhirsch42** [comment]
That would require duplicating a lot of styles and charting infrastructure.
There's a lot of charting stuff I'm not sure how to server render at all,
like the donut.

**Pull request merged**
